# Generated by Django 6.0.3 on 2026-04-03 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actus',
            fields=[
                ('datepubliee', models.DateField(auto_created=True)),
                ('IdAct', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='actus/')),
                ('mot_cle', models.CharField(max_length=100)),
                ('titre', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('IdEv', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='evenements/')),
                ('titre', models.CharField(max_length=100)),
                ('dateEv', models.DateField()),
                ('description', models.CharField(max_length=200)),
                ('nbrpersonnes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='membres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denomination', models.CharField(max_length=25)),
                ('nom', models.CharField(max_length=25)),
                ('prenom', models.CharField(max_length=25)),
                ('postnom', models.CharField(max_length=25)),
                ('localisation', models.CharField(max_length=25)),
                ('specificite', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('datepubliee', models.DateField(auto_created=True)),
                ('IdQuest', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=400)),
                ('nbrpersonnes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('Idservices', models.AutoField(primary_key=True, serialize=False)),
                ('Icon', models.ImageField(upload_to='services/')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('IdAdmin', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=25)),
                ('postnom', models.CharField(max_length=25)),
                ('prenom', models.CharField(max_length=25)),
                ('IdAct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestAGORA.actus', verbose_name='Actus')),
                ('IdEv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestAGORA.evenement', verbose_name='Id Evenements')),
                ('IdQuest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestAGORA.question', verbose_name='Id Question')),
                ('Idservices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestAGORA.services', verbose_name='Id Services')),
            ],
        ),
    ]
