# Generated by Django 6.0.3 on 2026-04-03 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestAGORA', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membres',
            name='img',
            field=models.ImageField(default='membres/', upload_to='membres/'),
        ),
        migrations.AlterField(
            model_name='actus',
            name='datepubliee',
            field=models.DateField(auto_created=True, default='23/12/2007'),
        ),
        migrations.AlterField(
            model_name='actus',
            name='description',
            field=models.CharField(default='kkk', max_length=200),
        ),
        migrations.AlterField(
            model_name='actus',
            name='img',
            field=models.ImageField(default='actus/', upload_to='actus/'),
        ),
        migrations.AlterField(
            model_name='actus',
            name='mot_cle',
            field=models.CharField(default='kkk', max_length=100),
        ),
        migrations.AlterField(
            model_name='actus',
            name='titre',
            field=models.CharField(default='kkk', max_length=100),
        ),
        migrations.AlterField(
            model_name='admin',
            name='nom',
            field=models.CharField(default='kkk', max_length=25),
        ),
        migrations.AlterField(
            model_name='admin',
            name='postnom',
            field=models.CharField(default='kkk', max_length=25),
        ),
        migrations.AlterField(
            model_name='admin',
            name='prenom',
            field=models.CharField(default='kkk', max_length=25),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='dateEv',
            field=models.DateField(default='23/12/2007'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='description',
            field=models.CharField(default='kkk', max_length=200),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='nbrpersonnes',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='titre',
            field=models.CharField(default='kkk', max_length=100),
        ),
        migrations.AlterField(
            model_name='membres',
            name='denomination',
            field=models.CharField(default='kkk', max_length=25),
        ),
        migrations.AlterField(
            model_name='membres',
            name='localisation',
            field=models.CharField(default='kkk', max_length=25),
        ),
        migrations.AlterField(
            model_name='membres',
            name='nom',
            field=models.CharField(default='kkk', max_length=25),
        ),
        migrations.AlterField(
            model_name='membres',
            name='postnom',
            field=models.CharField(default='kkk', max_length=25),
        ),
        migrations.AlterField(
            model_name='membres',
            name='prenom',
            field=models.CharField(default='kkk', max_length=25),
        ),
        migrations.AlterField(
            model_name='membres',
            name='specificite',
            field=models.CharField(default='kkk', max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='message',
            field=models.CharField(default='kkk', max_length=400),
        ),
        migrations.AlterField(
            model_name='question',
            name='nbrpersonnes',
            field=models.IntegerField(default=21),
        ),
        migrations.AlterField(
            model_name='question',
            name='titre',
            field=models.CharField(default='kkk', max_length=100),
        ),
        migrations.AlterField(
            model_name='services',
            name='description',
            field=models.CharField(default='ddd', max_length=200),
        ),
        migrations.AlterField(
            model_name='services',
            name='titre',
            field=models.CharField(default='lll', max_length=100),
        ),
    ]
